### PR TITLE
Kimani trevor darkmode

### PR DESCRIPTION
**Pull request by m-kimani**

### CODE REVIEW

**Review by FDDTheLucario — CHANGES_REQUESTED** [review]
- requires javadoc-style comments over custom functions
- requires additional comments to clarify throughout the code

**Review by FDDTheLucario — CHANGES_REQUESTED** [review]
- improve addItemToCart documentation
- add semicolons where they are missing

**Review by FDDTheLucario — CHANGES_REQUESTED** [review]
- rename Narbar.tsx to Navbar.tsx

**Review by SosaTheHustler — APPROVED** [review]

**Review by FDDTheLucario — APPROVED** [review]
- todo: add commenting to cart.tsx

**Pull request merged**
